### ISSUE TITLE
AttributeError: 'DocvqaExample' object has no attribute 'answers'

### ISSUE THREAD

**Issue by powerzist** [anisha2102/docvqa#15]
I encountered an error.

Traceback (most recent call last):
  File "run_docvqa.py", line 850, in <module>
    main()
  File "run_docvqa.py", line 744, in main
    args, train_dataset, model, tokenizer, labels, pad_token_label_id
  File "run_docvqa.py", line 251, in train
    mode="dev",
  File "run_docvqa.py", line 366, in evaluate
    results = squad_evaluate(examples, predictions)
  File "my_path/squad_metrics.py", line 212, in squad_evaluate
    qas_id_to_has_answer = {example.qas_id: bool(example.answers) for example in examples}
  File "my_path/squad_metrics.py", line 212, in <dictcomp>
    qas_id_to_has_answer = {example.qas_id: bool(example.answers) for example in examples}
AttributeError: 'DocvqaExample' object has no attribute 'answers'

```
class DocvqaExample(object):
    """A single training/test example for token classification."""


    def __init__(self,
               qas_id,
               question_text,
               doc_tokens,
               orig_answer_text=None,
               start_position=None,
               end_position=None,
               is_impossible=False,
               boxes = []):
        self.qas_id = qas_id
        self.question_text = question_text
        self.doc_tokens = doc_tokens
        self.orig_answer_text = orig_answer_text
        self.start_position = start_position
        self.end_position = end_position
        self.is_impossible = is_impossible
        self.boxes = boxes
```

I checked that class DocvqaExample has no attribute 'answers'.

```
def squad_evaluate(examples, preds, no_answer_probs=None, no_answer_probability_threshold=1.0):
    qas_id_to_has_answer = {example.qas_id: bool(example.answers) for example in examples}
    has_answer_qids = [qas_id for qas_id, has_answer in qas_id_to_has_answer.items() if has_answer]
    no_answer_qids = [qas_id for qas_id, has_answer in qas_id_to_has_answer.items() if not has_answer]

    if no_answer_probs is None:
        no_answer_probs = {k: 0.0 for k in preds}

    exact, f1 = get_raw_scores(examples, preds)

    exact_threshold = apply_no_ans_threshold(
        exact, no_answer_probs, qas_id_to_has_answer, no_answer_probability_threshold
    )
    f1_threshold = apply_no_ans_threshold(f1, no_answer_probs, qas_id_to_has_answer, no_answer_probability_threshold)

    evaluation = make_eval_dict(exact_threshold, f1_threshold)

    if has_answer_qids:
        has_ans_eval = make_eval_dict(exact_threshold, f1_threshold, qid_list=has_answer_qids)
        merge_eval(evaluation, has_ans_eval, "HasAns")

    if no_answer_qids:
        no_ans_eval = make_eval_dict(exact_threshold, f1_threshold, qid_list=no_answer_qids)
        merge_eval(evaluation, no_ans_eval, "NoAns")

    if no_answer_probs:
        find_all_best_thresh(evaluation, preds, exact, f1, no_answer_probs, qas_id_to_has_answer)

    return evaluation
```

My transformers version is 2.8.0.
What should I do?
Please, anyone give me some help.

**Comment by Mind-AI-Bots** [comment]
@powerzist  Did you rectified this error. because even I am facing the same issue.

**Comment by DapadaTony** [comment]
> @powerzist Did you rectified this error. because even I am facing the same issue.

I remember that was a problem version conflict, but not sure.
I was not able to change my version of libraries, so I couldn't try anymore.

**Comment by powerzist** [comment]
> @powerzist Did you rectified this error. because even I am facing the same issue.

I remember that was a problem version conflict, but not sure.
I was not able to change my version of libraries, so I couldn't try anymore.

**Comment by powerzist** [comment]
> @powerzist Did you rectified this error. because even I am facing the same issue.

I remember that was a problem of version conflict, but not sure.
I was not able to change my version of libraries, so I couldn't try anymore.
